# Generated by Django 3.2.25 on 2025-01-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeWireapp', '0008_teacher_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
