# Generated by Django 5.1 on 2025-01-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeWireapp', '0009_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default=' ', max_length=30, unique=True),
        ),
    ]
